# docker-compose.yml (usando porta 27018 para evitar conflitos)
services:
  hackathon-api:
    build: .
    container_name: hackathon-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://admin:password123@hackathon-mongodb:27017/hackathon-db?authSource=admin
      - JWT_SECRET=hackathon2025_super_secret_key_que_deve_ter_pelo_menos_32_caracteres_para_ser_seguro
      - JWT_EXPIRES_IN=7d
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - hackathon-mongodb
    networks:
      - hackathon-network
    command: npm run dev

  hackathon-mongodb:
    image: mongo:7-jammy
    container_name: hackathon-mongodb
    ports:
      - "27018:27017"  # MUDANÇA: porta externa 27018, interna 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: hackathon-db
    volumes:
      - mongodb_data:/data/db
    networks:
      - hackathon-network

volumes:
  mongodb_data:

networks:
  hackathon-network:
    driver: bridge